services:
  mysql:
    image: mysql:8.0
    container_name: elite
    restart: unless-stopped
    ports:
      - '${DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: '${DB_PASSWORD:+no}${DB_PASSWORD:-yes}'
      MYSQL_DATABASE: '${DB_DATABASE:-elite_watches}'
      MYSQL_USER: '${DB_USERNAME:-elite}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - elite-mysql-data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-proot']
      retries: 5
      timeout: 5s

volumes:
  elite-mysql-data:
    name: elite-mysql-data
